upload_files:
  stage: package
  script:
    - echo "Uploading scripts and files to the GitLab Package Registry"
    - mkdir -p $CI_PROJECT_DIR/artifacts  # Create a directory for artifacts
    - cp -r $CI_PROJECT_DIR/spin_container/* $CI_PROJECT_DIR/artifacts/  # Copy the contents of spin_container to the artifacts directory
    - tar czvf $CI_PROJECT_DIR/my-artifacts.tar.gz -C $CI_PROJECT_DIR artifacts/  # Create a tar.gz archive of the artifacts directory
  artifacts:
    paths:
      - $CI_PROJECT_DIR/my-artifacts.tar.gz  # Define the artifact to be passed to the next stage
  only:
    - master  # Trigger this job only on the master branch or any other branch as needed
